// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apbwihtsrissyziskgeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYndpaHRzcmlzc3l6aXNrZ2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzUyOTIsImV4cCI6MjA2Njg1MTI5Mn0.pseYjuEDw98bGyRmJkXBGEP7gsWK2RFo-sHbcubUONg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});